name = "soupon2gou-portfolio"
compatibility_date = "2024-08-16"

[env.production]
account_id = ""
pages_build_output_dir = "."

[[env.production.pages_build_config]]
build_command = ""
destination_dir = "."

[pages]
build_output_dir = "."
build_command = ""

